### ISSUE TITLE
Two README.md recommendations

### ISSUE THREAD

**Issue by flacle** [orson1282/arubabank_api#1]
Hi @orson1282 ,

Just a couple of preliminary observations... it might make sense to switch the order of Usage and Getting Started, with Getting Started showing up first then Usage, as usually an installation would precede usage when setting up software. This [blog](https://bulldogjob.com/news/449-how-to-write-a-good-readme-for-your-github-project) provides some good tips on how to structure a readme, in this example they have the order of technologies -> launch.

My other suggestion is on the Getting Started section, currently it states:
```
./setup.py install                               # install all dependencies
```
However it will happen that you don't have permissions to install so perhaps a surefire way to prevent permission errors is to adapt this to:
```
sudo python3 ./setup.py install                  # install all dependencies
```

**Comment by flacle** [comment]
Let me know if you would like me to submit a PR for this.

**Comment by orson1282** [comment]
Done. Thx for the tip. 👍
