### ISSUE TITLE
Add ability to persist a connection

### ISSUE THREAD

**Issue by flacle** [orson1282/arubabank_api#2]
At the moment, a user generates a new token and uses that token to retrieve data and the script terminates. Following @orson1282 request, there should be an active mode where the script keeps the connection open to listen for future events. This prevents the user from having to generate a new token every time.

The use case is for a transaction booking system where new transactions are passed along to the output/file.

Back-of-the-envelope idea goes as follows:
1) User provides command in console with an attribute that distinguishes between passive and active mode (defaults to passive) and is maybe backwards compatible with version 0.0.1.
2) If user specifies the active mode then session persists and a record/hash of the current state of transactions is kept in memory.
3) An interval (TBD) fetches transactions. If it's content does not match the current record/hash in memory then both the transactions file on disk and the record/hash in memory are updated.
4) Finally new transactions are outputted to the console, which can be piped to for example another file or some other executable.

**Comment by orson1282** [comment]
Thanks for building it 👍
