### ISSUE TITLE
Handle failed logins

### ISSUE THREAD

**Issue by flacle** [orson1282/arubabank_api#5]
Logic is currently missing for handling login responses.

**Comment by orson1282** [comment]
I think we can do a try except block.
200 = OK
401 = Unauthorized (So most likely invalid username/password)
404 = Not found (Aruba Bank down, or doing maintenance, or api changed)
Else = Unknown error ?

**Comment by orson1282** [comment]
Fixed in latest development version with a try/except block for connectionerror and httperror. Feel free to check it out and provide feedback. Thanks! 👍

**Comment by orson1282** [comment]
Failed logins handled in v0.2.0
